// Patisserie Postcard: authentication is compact, friendly, and framed as returning to a familiar counter.
import { ArrowRight, CakeSlice, Eye, EyeOff, KeyRound, Mail } from "lucide-react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { login, register as registerUser } from "../services/auth.service";
import { useAppStore } from "../store/useAppStore";
import { useLocale } from "../contexts/LocaleContext";
import { demoUser } from "../data/mockData";

const getLoginSchema = (t) => z.object({ email: z.string().email(t("validation.validEmail")), password: z.string().min(6, t("validation.password")), remember: z.boolean().optional() });
const getRegisterSchema = (t) => getLoginSchema(t).extend({ name: z.string().min(2, t("validation.name")), phone: z.string().min(7, t("validation.phone")), confirmPassword: z.string().min(6, t("validation.confirmPassword")) }).refine((values) => values.password === values.confirmPassword, { path: ["confirmPassword"], message: t("validation.passwordMatch") });

export function AuthPage({ mode = "login" }) {
  const { t } = useLocale(); const navigate = useNavigate(); const location = useLocation(); const setUser = useAppStore((state) => state.setUser); const [showPassword, setShowPassword] = useState(false); const isRegister = mode === "register"; const schema = isRegister ? getRegisterSchema(t) : getLoginSchema(t); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: zodResolver(schema), defaultValues: { email: "eden@example.com", password: "cakely", ...(isRegister ? { name: "", phone: "", confirmPassword: "" } : { remember: true }) } });
  async function submit(values) { try { const user = isRegister ? await registerUser(values) : await login(values); setUser(user); toast.success(isRegister ? t("auth.created") : t("auth.signedIn")); navigate(location.state?.from?.pathname || "/account"); } catch (error) { toast.error(error.message || t("auth.error")); } }
  function openDemoOwner() { setUser(demoUser); toast.success(t("owner.demoOpened")); navigate("/owner"); }
  return <section className="auth-page"><div className="auth-art"><div className="auth-arch"><CakeSlice size={42} /><p>Made for the moments<br />you will <em>remember.</em></p></div></div><div className="auth-form-wrap"><Link className="brand auth-brand" to="/"><CakeSlice size={24} /><span>Cakely</span></Link><div className="auth-form-box"><p className="section-kicker">{isRegister ? t("auth.registerKicker") : t("auth.loginKicker")}</p><h1>{isRegister ? <>{t("auth.registerTitleA")} <em>{t("auth.registerTitleB")}</em></> : <>{t("auth.loginTitleA")} <em>{t("auth.loginTitleB")}</em></>}</h1><p>{isRegister ? t("auth.registerIntro") : t("auth.loginIntro")}</p><form onSubmit={handleSubmit(submit)}>{isRegister && <AuthField label={t("auth.name")} error={errors.name?.message}><input className="form-input" placeholder={t("auth.yourName")} {...register("name")} /></AuthField>}<AuthField label={t("auth.email")} error={errors.email?.message}><input type="email" className="form-input" {...register("email")} /></AuthField>{isRegister && <AuthField label={t("auth.phone")} error={errors.phone?.message}><input className="form-input" placeholder="+251..." {...register("phone")} /></AuthField>}<AuthField label={t("auth.password")} error={errors.password?.message}><div className="password-input"><input type={showPassword ? "text" : "password"} className="form-input" {...register("password")} /><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? t("auth.hidePassword") : t("auth.showPassword")}>{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></AuthField>{isRegister && <AuthField label={t("auth.confirmPassword")} error={errors.confirmPassword?.message}><input type={showPassword ? "text" : "password"} className="form-input" {...register("confirmPassword")} /></AuthField>}{!isRegister && <div className="auth-options"><label><input type="checkbox" {...register("remember")} /> {t("auth.remember")}</label><Link to="/forgot-password">{t("auth.forgot")}</Link></div>}<button disabled={isSubmitting} className="btn-berry w-full mt-6">{isSubmitting ? t("auth.justMoment") : isRegister ? t("auth.create") : t("auth.signIn")} <ArrowRight size={17} /></button></form>{!isRegister && <div className="demo-owner-entry"><p>{t("owner.demoNote")}</p><button type="button" className="btn-outline w-full" onClick={openDemoOwner}>{t("owner.demoAccess")}</button></div>}<p className="auth-switch">{isRegister ? t("auth.already") : t("auth.newHere")} <Link to={isRegister ? "/login" : "/register"}>{isRegister ? t("auth.signIn") : t("auth.create")}</Link></p></div></div></section>;
}
function AuthField({ label, error, children }) { return <label className="field"><span className="form-label">{label}</span>{children}{error && <span className="field-error">{error}</span>}</label>; }
export function PasswordPage({ reset = false }) { const { t } = useLocale(); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: zodResolver(z.object({ email: z.string().email(t("validation.validEmail")) })), defaultValues: { email: "" } }); function submit() { toast.success(reset ? t("auth.resetDone") : t("auth.resetSent")); } return <section className="password-page page-width"><div className="password-card"><div className="password-icon">{reset ? <KeyRound /> : <Mail />}</div><p className="section-kicker">{reset ? t("auth.newPassword") : t("auth.resetKicker")}</p><h1>{reset ? t("auth.resetTitle") : t("auth.forgotTitle")}</h1><p>{reset ? t("auth.resetCopy") : t("auth.forgotCopy")}</p><form onSubmit={handleSubmit(submit)}><label className="form-label">{t("auth.email")}</label><input className="form-input" type="email" {...register("email")} />{errors.email && <p className="field-error">{errors.email.message}</p>}<button className="btn-berry mt-5 w-full" disabled={isSubmitting}>{reset ? t("auth.resetButton") : t("auth.sendButton")}</button></form><Link to="/login" className="text-link mt-6">{t("auth.back")} <ArrowRight size={16} /></Link></div></section>; }
