import { BarChart3, CakeSlice, Check, ChevronRight, CircleDollarSign, ClipboardList, Download, Eye, LayoutDashboard, LogOut, Package, Pencil, Plus, Store, Users, Warehouse, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { useLocale } from "../contexts/LocaleContext";
import { useAppStore } from "../store/useAppStore";
import { categories, statusMeta } from "../data/mockData";
import { formatPrice } from "../lib/format";
import { getOwnerWorkspace, saveOwnerCake, saveOwnerProfile, toggleOwnerCake, updateOwnerOrder } from "../services/tenant.service";

const ownerNav = [
  { id: "overview", label: "overview", icon: LayoutDashboard },
  { id: "catalogue", label: "catalogue", icon: CakeSlice },
  { id: "orders", label: "orders", icon: Package },
  { id: "finance", label: "finance", icon: BarChart3 },
  { id: "profile", label: "profile", icon: Store },
  { id: "operations", label: "operations", icon: ClipboardList },
];

function OwnerStatus({ status, t }) { return <span className={`status-pill status-${status}`}>{t(`status.${status}`)}</span>; }

export default function OwnerWorkspace() {
  const { t } = useLocale();
  const user = useAppStore((state) => state.user);
  const [active, setActive] = useState("overview");
  const [workspace, setWorkspace] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let alive = true; getOwnerWorkspace(user.id).then((data) => { if (alive) setWorkspace(data); }).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [user.id]);
  if (loading || !workspace) return <div className="owner-loading page-width"><span className="loading-dot" /><p>{t("owner.loading")}</p></div>;
  const refresh = async () => setWorkspace(await getOwnerWorkspace(user.id));
  const page = { overview: <OwnerOverview workspace={workspace} onNavigate={setActive} t={t} />, catalogue: <OwnerCatalogue workspace={workspace} onRefresh={refresh} t={t} />, orders: <OwnerOrders workspace={workspace} onRefresh={refresh} t={t} />, finance: <OwnerFinance workspace={workspace} t={t} />, profile: <OwnerProfile workspace={workspace} onRefresh={refresh} t={t} />, operations: <OwnerOperations workspace={workspace} t={t} /> }[active];
  return <div className="owner-shell"><aside className="owner-sidebar"><div className="owner-brand"><Link className="brand" to="/"><span className="brand-mark"><img src={workspace.tenant.logo} alt="" /><CakeSlice /></span><span>{workspace.tenant.name}</span></Link><span className="owner-badge">{t("owner.workspace")}</span></div><nav className="owner-nav" aria-label={t("owner.workspace")}>{ownerNav.map(({ id, label, icon: Icon }) => <button className={active === id ? "active" : ""} onClick={() => setActive(id)} key={id}><Icon size={18} />{t(`owner.${label}`)}</button>)}</nav><div className="owner-side-bottom"><Link to={`/bakeries/${workspace.tenant.slug}`}><Eye size={17} />{t("owner.viewShop")}</Link><Link to="/"><LogOut size={17} />{t("owner.backStorefront")}</Link></div></aside><main className="owner-main"><header className="owner-topbar"><div><p className="eyebrow">{t("owner.workspace")}</p><h1>{workspace.tenant.name}</h1></div><div className="owner-top-actions"><span className="published-dot"><i />{workspace.tenant.isPublished ? t("owner.published") : t("owner.draft")}</span><Link className="btn-berry" to={`/bakeries/${workspace.tenant.slug}`}><Eye size={16} />{t("owner.viewShop")}</Link></div></header><section className="owner-content">{page}</section></main></div>;
}

function OwnerOverview({ workspace, onNavigate, t }) {
  const pending = workspace.orders.filter((order) => ["pending", "confirmed", "preparing"].includes(order.status)).length;
  const cards = [{ label: t("owner.today"), value: workspace.orders.length, note: t("owner.ordersThisPeriod"), icon: Package }, { label: t("owner.revenue"), value: formatPrice(workspace.finance.grossSales), note: t("owner.range"), icon: CircleDollarSign }, { label: t("owner.pending"), value: pending, note: t("owner.needAttention"), icon: ClockIcon }, { label: t("owner.active"), value: workspace.menu.filter((cake) => cake.available).length, note: t("owner.catalogueLive"), icon: CakeSlice }];
  return <><section className="owner-welcome"><div><p className="section-kicker">{t("owner.welcomeKicker")}</p><h2>{t("owner.welcome")}</h2><p>{t("owner.intro")}</p></div><Link className="btn-outline" to={`/bakeries/${workspace.tenant.slug}`}><Eye size={16} />{t("owner.viewShop")}</Link></section><div className="owner-metric-grid">{cards.map(({ label, value, note, icon: Icon }) => <article key={label}><span className="owner-metric-icon"><Icon size={18} /></span><p>{label}</p><strong>{value}</strong><small>{note}</small></article>)}</div><div className="owner-overview-grid"><section className="owner-card"><div className="owner-card-head"><div><p className="eyebrow">{t("owner.orders")}</p><h3>{t("owner.recentOrders")}</h3></div><button className="text-link" onClick={() => onNavigate("orders")}>{t("owner.viewAll")} <ChevronRight size={14} /></button></div>{workspace.orders.slice(0, 4).map((order) => <div className="owner-order-row" key={order.id}><div><strong>#{order.id}</strong><span>{order.items[0]?.name}</span></div><OwnerStatus status={order.status} t={t} /><b>{formatPrice(order.total)}</b></div>)}</section><section className="owner-card owner-publish-card"><div className="publish-stamp"><Store size={20} /></div><p className="eyebrow">{t("owner.globalCounter")}</p><h3>{workspace.tenant.isPublished ? t("owner.shopLive") : t("owner.shopDraft")}</h3><p>{t("owner.globalCopy")}</p><Link className="btn-berry" to={`/bakeries/${workspace.tenant.slug}`}>{t("owner.viewShop")} <ChevronRight size={16} /></Link></section></div></>;
}

function ClockIcon(props) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" {...props}><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></svg>; }

function OwnerCatalogue({ workspace, onRefresh, t }) {
  const [editor, setEditor] = useState(null); const [query, setQuery] = useState(""); const filtered = useMemo(() => workspace.menu.filter((cake) => cake.name.toLowerCase().includes(query.toLowerCase())), [workspace.menu, query]);
  async function save(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const name = form.get("name").trim(); const price = Number(form.get("price")); const imageFile = form.get("image"); if (!name || !price) return toast.error(t("validation.ownerCake")); const image = imageFile && imageFile.size ? URL.createObjectURL(imageFile) : editor?.image || workspace.menu[0]?.image; await saveOwnerCake(workspace.tenant.ownerId, { id: editor?.id, name, category: form.get("category"), flavor: form.get("flavor"), description: form.get("description"), price, image, available: form.get("available") === "on", featured: form.get("featured") === "on" }); setEditor(null); await onRefresh(); toast.success(t("owner.savedCake")); }
  return <><div className="owner-page-head"><div><p className="section-kicker">{t("owner.catalogue")}</p><h2>{t("owner.catalogueTitle")}</h2><p>{t("owner.catalogueCopy")}</p></div><button className="btn-berry" onClick={() => setEditor({})}><Plus size={16} />{t("owner.addCake")}</button></div><div className="owner-toolbar"><label className="admin-search"><Pencil size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("owner.search")} /></label><span>{filtered.length} {t("owner.cakesCount")}</span></div><div className="owner-catalogue-grid">{filtered.map((cake) => <article className="owner-cake-card" key={cake.id}><img src={cake.image} alt="" /><div className="owner-cake-card-body"><div className="owner-cake-card-top"><span className={cake.available ? "availability available" : "availability hidden"}><i />{cake.available ? t("owner.available") : t("owner.hidden")}</span><button className="icon-button" onClick={() => setEditor(cake)} aria-label={`${t("owner.edit")} ${cake.name}`}><Pencil size={15} /></button></div><h3>{cake.name}</h3><p>{cake.category} · {cake.flavor}</p><strong>{formatPrice(cake.price)}</strong><label className="owner-toggle"><input type="checkbox" checked={cake.available} onChange={async (event) => { await toggleOwnerCake(workspace.tenant.ownerId, cake.id, event.target.checked); await onRefresh(); toast.success(event.target.checked ? t("owner.publishedCake") : t("owner.hiddenCake")); }} /><span><i /></span><small>{cake.available ? t("owner.available") : t("owner.hidden")}</small></label></div></article>)}</div>{editor && <CakeEditor cake={editor} onClose={() => setEditor(null)} onSave={save} t={t} />}</>;
}

function CakeEditor({ cake, onClose, onSave, t }) { return <div className="owner-modal"><form className="owner-editor-card" onSubmit={onSave}><button type="button" className="icon-button owner-modal-close" onClick={onClose} aria-label={t("common.close")}><X size={17} /></button><p className="section-kicker">{cake.id ? t("owner.editCake") : t("owner.newCake")}</p><h2>{cake.id ? cake.name : t("owner.addCake")}</h2><div className="owner-editor-fields"><label className="field"><span className="form-label">{t("owner.name")}</span><input className="form-input" name="name" defaultValue={cake.name} autoFocus /></label><label className="field"><span className="form-label">{t("owner.category")}</span><select className="form-select" name="category" defaultValue={cake.category || categories[0].name}>{categories.map((item) => <option key={item.id}>{item.name}</option>)}</select></label><label className="field"><span className="form-label">{t("owner.price")}</span><input className="form-input" type="number" min="1" name="price" defaultValue={cake.price || ""} /></label><label className="field"><span className="form-label">{t("owner.flavor")}</span><input className="form-input" name="flavor" defaultValue={cake.flavor || "Vanilla & raspberry"} /></label><label className="field owner-editor-full"><span className="form-label">{t("owner.description")}</span><textarea className="form-textarea" name="description" defaultValue={cake.description || ""} /></label><label className="field owner-editor-full owner-upload-field"><span className="form-label">{t("owner.image")}</span><input className="form-input" type="file" name="image" accept="image/png,image/jpeg,image/webp" /> <small>{t("owner.uploadHint")}</small></label><label className="owner-check"><input type="checkbox" name="available" defaultChecked={cake.available !== false} />{t("owner.available")}</label><label className="owner-check"><input type="checkbox" name="featured" defaultChecked={cake.featured} />{t("owner.featured")}</label></div><div className="owner-editor-actions"><button type="button" className="btn-outline" onClick={onClose}>{t("owner.cancel")}</button><button className="btn-berry"><Check size={16} />{t("owner.save")}</button></div></form></div>; }

function OwnerOrders({ workspace, onRefresh, t }) { return <><div className="owner-page-head"><div><p className="section-kicker">{t("owner.orders")}</p><h2>{t("owner.orderTitle")}</h2><p>{t("owner.orderCopy")}</p></div></div><section className="owner-card owner-orders-card"><div className="owner-table owner-orders-table"><div className="owner-table-head"><span>{t("owner.order")}</span><span>{t("owner.customer")}</span><span>{t("owner.value")}</span><span>{t("owner.status")}</span></div>{workspace.orders.map((order) => <div className="owner-table-row" key={order.id}><div><strong>#{order.id}</strong><small>{order.items.map((item) => item.name).join(", ")}</small></div><span>{order.customer?.name || t("owner.guestCustomer")}</span><strong>{formatPrice(order.total)}</strong><select value={order.status} className="status-select" onChange={async (event) => { await updateOwnerOrder(workspace.tenant.ownerId, order.id, event.target.value); await onRefresh(); toast.success(t("owner.orderUpdated")); }}>{Object.keys(statusMeta).map((key) => <option value={key} key={key}>{t(`status.${key}`)}</option>)}</select></div>)}</div></section></>; }

function OwnerFinance({ workspace, t }) {
  const { finance } = workspace;
  const maxRevenue = Math.max(...finance.monthlyRevenue.map((point) => point.value));
  const maxCakeOrders = Math.max(...finance.topCakes.map((cake) => cake.orders));
  const chartWidth = 620;
  const chartHeight = 220;
  const points = finance.monthlyRevenue.map((point, index) => ({ ...point, x: 28 + (index * (chartWidth - 56)) / Math.max(1, finance.monthlyRevenue.length - 1), y: chartHeight - 28 - (point.value / maxRevenue) * (chartHeight - 58) }));
  const path = points.map((point, index) => `${index === 0 ? "M" : "L"} ${point.x} ${point.y}`).join(" ");
  return <><div className="owner-page-head"><div><p className="section-kicker">{t("owner.finance")}</p><h2>{t("owner.financeTitle")}</h2><p>{t("owner.financeCopy")}</p></div><span className="owner-range">{t("owner.range")}</span></div><div className="finance-summary-grid"><article><span>{t("owner.gross")}</span><strong>{formatPrice(finance.grossSales)}</strong><small>+12.4%</small></article><article><span>{t("owner.fees")}</span><strong>{formatPrice(finance.platformFees)}</strong><small>{t("owner.platformFeeNote")}</small></article><article><span>{t("owner.payout")}</span><strong>{formatPrice(finance.readyForPayout)}</strong><small>{finance.payoutDate}</small></article><article><span>{t("owner.ordersValue")}</span><strong>{formatPrice(finance.averageOrder)}</strong><small>{t("owner.averageOrder")}</small></article></div><div className="finance-chart-grid"><section className="owner-card finance-chart-card"><div className="owner-card-head"><div><p className="eyebrow">{t("owner.salesPulse")}</p><h3>{t("owner.monthlyRevenue")}</h3></div><CircleDollarSign size={21} /></div><div className="finance-line-chart"><svg viewBox={`0 0 ${chartWidth} ${chartHeight}`} role="img" aria-label={t("owner.monthlyRevenue")}><defs><linearGradient id="revenue-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#c93665" stopOpacity=".28" /><stop offset="100%" stopColor="#c93665" stopOpacity="0" /></linearGradient></defs><path d={`${path} L ${points.at(-1)?.x ?? 28} ${chartHeight - 28} L ${points[0]?.x ?? 28} ${chartHeight - 28} Z`} fill="url(#revenue-fill)" /><path d={path} fill="none" stroke="#c93665" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />{points.map((point) => <g key={point.month}><circle cx={point.x} cy={point.y} r="6" fill="#fffaf4" stroke="#c93665" strokeWidth="3" /><text x={point.x} y={chartHeight - 6} textAnchor="middle">{point.month}</text><title>{`${point.month}: ${formatPrice(point.value)}`}</title></g>)}</svg></div></section><section className="owner-card finance-chart-card"><div className="owner-card-head"><div><p className="eyebrow">{t("owner.catalogue")}</p><h3>{t("owner.topCakes")}</h3></div><CakeSlice size={21} /></div><div className="top-cakes-chart">{finance.topCakes.map((cake) => <div className="top-cake-row" key={cake.name}><div className="top-cake-label"><strong>{cake.name}</strong><small>{cake.orders} {t("owner.chartOrders")} · {formatPrice(cake.revenue)}</small></div><div className="top-cake-track"><span style={{ width: `${Math.max(12, (cake.orders / maxCakeOrders) * 100)}%` }} /></div></div>)}</div></section></div></>;
}

function OwnerOperations({ workspace, t }) {
  const [active, setActive] = useState("inventory");
  const tabs = [{ id: "inventory", label: t("owner.inventory"), icon: Warehouse }, { id: "staff", label: t("owner.staff"), icon: Users }, { id: "reports", label: t("owner.reports"), icon: BarChart3 }];
  function exportReport() { const rows = [["Metric", "Value"], [t("owner.gross"), workspace.finance.grossSales], [t("owner.fees"), workspace.finance.platformFees], [t("owner.payout"), workspace.finance.readyForPayout]]; const blob = new Blob([rows.map((row) => row.join(",")).join("\\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "cakely-finance-report.csv"; anchor.click(); URL.revokeObjectURL(url); }
  return <><div className="owner-page-head"><div><p className="section-kicker">{t("owner.operations")}</p><h2>{t("owner.operations")}</h2><p>{t("owner.operationsCopy")}</p></div><span className="owner-range">{t("owner.comingSoon")}</span></div><div className="owner-operations-tabs" role="tablist" aria-label={t("owner.operations")}>{tabs.map(({ id, label, icon: Icon }) => <button type="button" role="tab" aria-selected={active === id} className={active === id ? "active" : ""} onClick={() => setActive(id)} key={id}><Icon size={16} aria-hidden="true" />{label}</button>)}</div>{active === "inventory" && <section className="owner-card operations-panel"><div className="owner-card-head"><div><p className="eyebrow">{t("owner.inventory")}</p><h3>{t("owner.inventoryCopy")}</h3></div><button type="button" className="btn-outline" onClick={() => toast.info(t("owner.connectBackend"))}>{t("owner.connectBackend")}</button></div><div className="inventory-readiness-list">{workspace.menu.map((cake) => <div key={cake.id}><span className={cake.available ? "availability available" : "availability hidden"}><i />{cake.available ? t("owner.available") : t("owner.hidden")}</span><strong>{cake.name}</strong><small>{cake.category} · {cake.flavor}</small></div>)}</div></section>}{active === "staff" && <section className="owner-card operations-panel"><div className="owner-card-head"><div><p className="eyebrow">{t("owner.staff")}</p><h3>{t("owner.staffCopy")}</h3></div><Users size={21} /></div><div className="operations-empty"><Users size={28} aria-hidden="true" /><p>{t("owner.connectBackend")}</p><small>{t("owner.staffCopy")}</small></div></section>}{active === "reports" && <section className="owner-card operations-panel"><div className="owner-card-head"><div><p className="eyebrow">{t("owner.reports")}</p><h3>{t("owner.reportsCopy")}</h3></div><button type="button" className="btn-berry" onClick={exportReport}><Download size={16} aria-hidden="true" />{t("owner.exportReport")}</button></div><div className="operations-report-grid"><article><span>{t("owner.gross")}</span><strong>{formatPrice(workspace.finance.grossSales)}</strong></article><article><span>{t("owner.fees")}</span><strong>{formatPrice(workspace.finance.platformFees)}</strong></article><article><span>{t("owner.payout")}</span><strong>{formatPrice(workspace.finance.readyForPayout)}</strong></article></div></section>}</>;
}

function OwnerProfile({ workspace, onRefresh, t }) { const [saved, setSaved] = useState(false); async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); await saveOwnerProfile(workspace.tenant.ownerId, { name: form.get("name"), city: form.get("city"), bio: form.get("bio"), slug: form.get("slug"), isPublished: form.get("isPublished") === "on" }); await onRefresh(); setSaved(true); toast.success(t("owner.profileSaved")); setTimeout(() => setSaved(false), 1800); } return <><div className="owner-page-head"><div><p className="section-kicker">{t("owner.profile")}</p><h2>{t("owner.profileTitle")}</h2><p>{t("owner.profileCopy")}</p></div><Link className="btn-outline" to={`/bakeries/${workspace.tenant.slug}`}><Eye size={16} />{t("owner.viewShop")}</Link></div><form className="owner-profile-card" onSubmit={submit}><div className="owner-profile-preview" style={{ backgroundImage: `url(${workspace.tenant.coverImage})` }}><div><img src={workspace.tenant.logo} alt="" /><span>{workspace.tenant.name}</span></div></div><div className="owner-profile-fields"><label className="field"><span className="form-label">{t("owner.shopName")}</span><input className="form-input" name="name" defaultValue={workspace.tenant.name} /></label><label className="field"><span className="form-label">{t("owner.city")}</span><input className="form-input" name="city" defaultValue={workspace.tenant.city} /></label><label className="field"><span className="form-label">{t("owner.slug")}</span><input className="form-input" name="slug" defaultValue={workspace.tenant.slug} /></label><label className="field owner-editor-full"><span className="form-label">{t("owner.bio")}</span><textarea className="form-textarea" name="bio" defaultValue={workspace.tenant.bio} /></label><label className="owner-publish-check"><input type="checkbox" name="isPublished" defaultChecked={workspace.tenant.isPublished} /><span><strong>{t("owner.publishShop")}</strong><small>{t("owner.publishShopCopy")}</small></span></label><button className="btn-berry" disabled={saved}>{saved ? <><Check size={16} />{t("owner.saved")}</> : t("owner.saveProfile")}</button></div></form></>; }
